# This file brings some extra configuration needed for local dev environment
# To start your local dev environment please run:
#    docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
version: "3.9"
services:
  designer:
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/model/node_modules
      - /usr/src/app/model/dist
      - /usr/src/app/designer/node_modules
      - /usr/src/app/designer/dist
      - /usr/src/app/runner/node_modules
      - /usr/src/app/runner/dist
      - ./designer:/usr/src/app/designer:delegated
    command: yarn designer dev
  runner:
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/model/node_modules
      - /usr/src/app/model/dist
      - /usr/src/app/designer/node_modules
      - /usr/src/app/designer/dist
      - /usr/src/app/runner/node_modules
      - /usr/src/app/runner/dist
      - ./runner:/usr/src/app/runner
    command: yarn runner dev
