# This file is used for the smoke tests
version: "3.9"
services:
  designer:
    container_name: designer
    image: digital-form-builder-designer
    build:
      context: .
      dockerfile: ./designer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123abc
      - sandbox=true
      - PREVIEW_URL=http://localhost:3009
      - PUBLISH_URL=http://runner:3009
    command: yarn designer start
    depends_on:
      - runner
  runner:
    container_name: runner
    image: digital-form-builder-runner
    build:
      context: .
      dockerfile: ./runner/Dockerfile
    ports:
      - "3009:3009"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123abc
      - sandbox=true
      - PREVIEW_MODE=true
      - NODE_ENV=test
    command: yarn runner start
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123abc
    ports:
      - "6379:6379"
