export enum ListActions {
  EDIT_LIST = "EDIT_LIST",

  EDIT_TITLE = "EDIT_TITLE",

  SET_SELECTED_LIST = "SET_SELECTED_LIST",
  ADD_NEW_LIST = "ADD_NEW_LIST",

  ADD_LIST_ITEM = "ADD_LIST_ITEM",
  EDIT_LIST_VALUE_TYPE = "EDIT_LIST_VALUE_TYPE",
  EDIT_LIST_ITEM = "EDIT_LIST_ITEM",
  DELETE_LIST_ITEM = "DELETE_LIST_ITEM",

  EDIT_LIST_ITEM_TEXT = "EDIT_LIST_ITEM_TEXT",
  EDIT_LIST_ITEM_DESCRIPTION = "EDIT_LIST_ITEM_DESCRIPTION",
  EDIT_LIST_ITEM_VALUE = "EDIT_LIST_ITEM_VALUE",
  EDIT_LIST_ITEM_CONDITION = "EDIT_LIST_ITEM_CONDITION",
  SUBMIT_LIST_ITEM = "SUBMIT_LIST_ITEM",
  LIST_VALIDATION_ERRORS = "LIST_VALIDATION_ERRORS",
  LIST_ITEM_VALIDATION_ERRORS = "LIST_ITEM_VALIDATION_ERRORS",

  SUBMIT = "SUBMIT",
  DESELECT_LIST_ITEM = "DESELECT_LIST_ITEM",
}
