name: Anchore scan

on:
  push:
    branches:
      - main
      - master
      - feature/FORMS-206-add-anchore-scans

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker compose pull
        run: docker-compose pull
      - name: Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          # Layers are cached by keys
          # docker-layer-caching action has an issue which causes layers to dangle,
          # and this will eventually build up and increase pull time significantly
          # see https://github.com/satackey/action-docker-layer-caching/issues/55
          # ATM solution is to change keys periodically to avoid the dangling layers
          # for that just increase the number you see in key and restore-keys below (same number in both keys).
          key: digital-form-builder-1-{hash}
          restore-keys: |
            digital-form-builder-1
      - name: Docker compose build
        run: |
          LAST_TAG='${{ github.run_number }}-rc'
          LAST_COMMIT='${{ github.sha }}'
          docker-compose build
      - name: Docker compose up
        run: docker-compose up -d
      - name: Check designer container is running
        run: |
          docker ps
          docker run --network container:designer appropriate/curl -4 --retry 10 --retry-connrefused --retry-delay 10 http://localhost:3000/
      - name: Check runner container is running
        run: |
          docker ps
          docker run --network container:runner appropriate/curl -4 --retry 10 --retry-connrefused --retry-delay 10 http://localhost:3009/

  runner-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "digital-form-builder_runner"
          fail-build: true
          severity-cutoff: critical
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: ${{ success() || failure() }}
        with:
          name: AnchoreReports-Runner
          path: vulnerabilities.json

  designer-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "digital-form-builder_designer"
          acs-report-enable: true
          fail-build: true
          severity-cutoff: critical
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: ${{ success() || failure() }}
        with:
          name: AnchoreReports-Designer
          path: vulnerabilities.json
