name: Anchore scan

on:
  push:
    branches:
      - main
      - master
      - feature/FORMS-206-add-anchore-scans

jobs:
  runner-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "ghcr.io/xgovformbuilder/digital-form-builder-runner:latest"
          fail-build: true
          severity-cutoff: critical
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: ${{ success() || failure() }}
        with:
          name: AnchoreReports-Runner
          path: vulnerabilities.json

  designer-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "ghcr.io/xgovformbuilder/digital-form-builder-designer:latest"
          acs-report-enable: true
          fail-build: true
          severity-cutoff: critical
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: ${{ success() || failure() }}
        with:
          name: AnchoreReports-Designer
          path: vulnerabilities.json
