name: Create UKHSA Release

on:
  push:
    branches:
      - v2
    paths:
      - "**/*docker-compose*.yml"
      - "**/*docker-compose*.yaml"
      - "**/docker-compose/**"
      - "/runner/**"
      - "/designer/**"
      - "/submitter/**"
      - "/model/**"
      - "/queue-model/**"
      - "package.json"
      - "yarn.lock"

jobs:
  create-extended-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Find merge base with main and create extended tags
        run: |
          # Ensure we have all tags and branches
          git fetch --tags origin
          git fetch origin main:main

          # Find the merge base between v2 and main
          MERGE_BASE=$(git merge-base v2 main)
          echo "Merge base commit: $MERGE_BASE"

          # Get the tags that point to the merge base commit
          BASE_TAGS=$(git tag --points-at $MERGE_BASE)

          if [ -z "$BASE_TAGS" ]; then
            echo "No tags found at merge base. Exiting."
            exit 0
          fi

          echo "Found tags at merge base: $BASE_TAGS"

          # Process each found tag
          for BASE_TAG in $BASE_TAGS; do
            echo "Processing base tag: $BASE_TAG"
            
            # Find highest existing extended tag version
            HIGHEST_EXT_VERSION=0
            
            # Get all extended tags for this base tag
            EXISTING_EXT_TAGS=$(git tag -l "${BASE_TAG}-ext*")
            
            for EXT_TAG in $EXISTING_EXT_TAGS; do
              # Extract version number after "ext"
              VERSION_NUM=$(echo $EXT_TAG | sed -E "s|${BASE_TAG}-ext([0-9]+)|\1|")
              
              if [[ $VERSION_NUM =~ ^[0-9]+$ ]]; then
                if [ $VERSION_NUM -gt $HIGHEST_EXT_VERSION ]; then
                  HIGHEST_EXT_VERSION=$VERSION_NUM
                fi
              fi
            done
            
            # Calculate new version
            NEW_VERSION=$((HIGHEST_EXT_VERSION + 1))
            NEW_TAG="${BASE_TAG}-ext${NEW_VERSION}"
            
            echo "Creating new extended tag: $NEW_TAG"
            
            # Get current v2 branch HEAD
            V2_HEAD=$(git rev-parse v2)
            
            # Create annotated tag
            git tag -a "$NEW_TAG" -m "Extended tag from $BASE_TAG for v2 branch (version $NEW_VERSION)" $V2_HEAD
            
            # Push the new tag
            git push origin "$NEW_TAG"
            echo "Successfully created and pushed tag $NEW_TAG"
          done
