name: Deploy to FCDO Environment

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Name of the app to deploy to heroku"
        required: true
      tag:
        description: "Tag to use for heroku deployments"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy development ${{ github.event.inputs.app }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
        run: heroku container:login

      - name: Pull latest ${{ github.event.inputs.app }} image
        run: docker pull ghcr.io/xgovformbuilder/digital-form-builder-${{ github.event.inputs.app }}:${{ github.event.inputs.tag }}

      - name: Tag Image
        run: docker tag ghcr.io/xgovformbuilder/digital-form-builder-${{ github.event.inputs.app }}:${{ github.event.inputs.tag }} registry.heroku.com/form-${{ github.event.inputs.app }}-fcdo/web

      - name: Push to Heroku Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
        run: docker push registry.heroku.com/form-${{ github.event.inputs.app }}-fcdo/web

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
        run: heroku container:release -a form-${{ github.event.inputs.app }}-fcdo web
