name: Increment version

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: "Get latest tag"
        id: latest_tag
        run: |
          echo "tag="$(git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/*") >> $GITHUB_OUTPUT

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.latest_tag.outputs.tag}}
          version-fragment: "bug"

      - name: Update version in dluhc-build-and-publish.yml
        id: update_version
        run: |
          echo Updating version from ${{ steps.latest_tag.outputs.tag}} to ${{ steps.bump_version.outputs.next-version }}
          sed -i 's/VERSION: "${{ steps.latest_tag.outputs.tag}}"/VERSION: "${{ steps.bump_version.outputs.next-version }}"/' .github/workflows/dluhc-build-and-publish.yml
          git config user.name 'FSD Github Actions'
          git add .github/workflows/dluhc-build-and-publish.yml
          git commit -m "Update version to ${{ steps.bump_version.outputs.next-version }}"
          git push origin $GITHUB_HEAD_REF
          echo "Updated dluhc-build-and-publish.yml with version ${{ steps.bump_version.outputs.next-version }}" >> $GITHUB_STEP_SUMMARY
