name: pa11y
on:
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - 'docs/**'
      - '**/README.md'
  workflow_dispatch:
jobs:  

  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Docker compose pull
        run: docker-compose pull
        # DAYOFYEAR key is used to rotate docker-layer-caching to avoid the layers dandle issue
        # see https://github.com/satackey/action-docker-layer-caching/issues/55
        # if you change this, please remember to apply the same changes to main--lint-unit-build-and-publish-images.yml
        # so main branch cache can be shared with branches
      - run: echo "DAYOFYEAR = $(date +%j)"
      - run: echo "DAYOFYEAR=$(date +%j)" >> $GITHUB_ENV
      - name: Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: digital-form-builder-${{ env.DAYOFYEAR }}-{hash}
          restore-keys: |
            digital-form-builder-${{ env.DAYOFYEAR }}
      - name: Create .env for ${{ matrix.app }} workspace
        run: |
          touch ./${{ matrix.app }}/.env
          echo LAST_TAG_GH=2.0.${{ github.run_number }}-rc >> ./${{ matrix.app }}/.env
          echo LAST_COMMIT_GH=${{ github.sha }} >> ./${{ matrix.app }}/.env
          cat ./${{ matrix.app }}/.env
      - name: Docker compose build
        run: |
          docker-compose build --parallel
      - name: Docker compose up
        run: docker-compose up -d
      - name: Install smoke tests dependencies
        run: yarn workspaces focus @xgovformbuilder/test
      - name: Install pa11y-ci
        run: npm install -g pa11y-ci
      - name: Check designer container is running
        run: |
          docker ps
          docker run --network container:designer appropriate/curl -4 --retry 10 --retry-connrefused --retry-delay 10 http://localhost:3000/
      - name: Check runner container is running
        run: |
          docker ps
          docker run --network container:runner appropriate/curl -4 --retry 10 --retry-connrefused --retry-delay 10 http://localhost:3009/
     
      - name: pa11y
        run: | 
          cd designer 
          npx pa11y-ci