name: Publish to Github Container Registry

on:
  push:
    branches: chore/STP-1037-1038

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ designer, runner ]
    steps:
      - name: Trigger deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy Development Environment
          token: ${{ secrets.GHCR_PAT }}
          inputs: '{ "app": "${{ matrix.app }}"}'
