name: Sync Upstream Semantic Version Tags

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC; adjust as needed

jobs:
  sync-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important: fetch the entire history including all tags

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/XGovFormBuilder/digital-form-builder || echo "Upstream remote already exists"

      - name: Fetch Tags from Upstream
        run: |
          git fetch upstream --tags

      - name: Sync Semantic Version Tags from Upstream
        run: |
          echo "Listing upstream tags..."
          tags=$(git ls-remote --tags upstream | grep -E 'refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(\^\{\})?$' | sed -E 's|refs/tags/([^\\^]+).*|\1|')

          if [ -z "$tags" ]; then
              echo "No matching semantic version tags found in upstream."
              exit 0
          else
              echo "Found tags: $tags"
          fi

          for tag in $tags; do
              if git rev-parse "$tag" >/dev/null 2>&1; then
              echo "Tag $tag already exists, skipping."
              else
              commit=$(git ls-remote --tags upstream "$tag" | grep -E "refs/tags/$tag(\\^\\{\\})?$" | awk '{print $1}' | head -n 1)
              echo "Creating tag $tag at commit $commit"
              git tag -a "$tag" -m "Synced $tag from upstream" "$commit"
              git push origin "$tag"
              fi
          done
